### PR TITLE
install new parent & child themes for v2.0

### PR DESCRIPTION
**Pull request by phil-evans**

### CODE REVIEW

**Comment by perronld** [comment]
There is also too many files under framework/resources/vendor.
For example, full aos source is in there, but only framework/resources/vendor/aos/dist/aos.css
framework/resources/vendor/aos/dist/aos.js are actually needed.

For bootstrap, do you think it's possible to do something similar? ( most likely only framework/resources/vendor/bootstrap/dist/css/bootstrap.min.css and framework/resources/vendor/bootstrap/dist/js/bootstrap.min.js or framework/resources/vendor/bootstrap/dist/js/bootstrap.bundle.js would be required)

font-awesome-pro is a little bit problematic... we are indirectly redistributing it by putting it in a open-source repository.. I think it will be safer to move this one out of the repository.. ( for example: under site/assets/vendor/font-awesome-pro ). I can easily add this to the docker image.

framework/resources/vendor/lottie-player-2.0.1 doesn't seem to be in use.. in functions.php, it is installed via unpkg.

So, by removing those unwanted files, the merge will be brought down to less than 120 files instead of 1820 (which hang in my browser).

Finally, if you agree, I would remove + ignore fw-child/resources/css/child.css, and update the climatedata-compose.yaml to compile it.

**Comment by phil-evans** [comment]
ok i think i've resolved all the issues mentioned above. notes:

- AOS & bootstrap: removed and ignored unneeded files (child.scss uses bootstrap imports)
- lottie-player: removed unused package
- font-awesome: removed from repo and changed style reference to site/assets/vendor/font-awesome-pro - please include in the image as mentioned (zip attached)
[font-awesome-pro.zip](https://github.com/CanadianClimateDataPortal/climatedata-wp-theme/files/12728165/font-awesome-pro.zip)
- child.css: removed compiled CSS

**Comment by francisPLT** [comment]
My comments are more comments and less "request for changes"

Overall I'm pretty satisfied by what I read; I mostly glaced the main Framework part past the few first files and concentrated on the fw-child part.

Good job in the last commits, I saw a few things I wanted to comment on before hand, only to comeback and see you had already fixed them!

@phil-evans Do you have any more work you wanted to include in this PR?

If now, I'd be ready to approve this PR unless the previous comment from @perronld is not yet resolved to his satisfaction, or @OlivGruwe has something to say.

**Review by francisPLT — APPROVED** [review]
Since there haven't been any more comments, I'm assuming the previous comments by @perronld have been addressed in a satisfactory way and the PR is finalized.

I'm therefore approving this PR.

**Pull request merged**
